(* ::Package:: *)

(* ::Input:: *)
(*ResourceFunction["ESMFoldProteinSequence"]["MSFTKWRRMMTGFRVQFSDQPNQVGTGVIDSGDGQKAVPDPQVDGTSFGAFILQSLITLRDPTRGPTSGAARLRBGPRRSLLTTRDLGLQLRTLLTGQLALLITQAIQLPLDD"]*)


(* ::Input:: *)
(*ResourceFunction["ESMFoldProteinSequence"]["MWGLSTETGSGRDSQSLFVIBHKLGLSGTMDLGYKQGLDYTALYDWIIGRDGWVSGTGTTPIAVTTGYTCIKQGLDPDWIGTRVDIPQASDQSAGDTWTDLDNGGYLA"]*)


(* ::Input:: *)
(*ESMFold[str_String]:= ResourceFunction["ESMFoldProteinSequence"][str]*)


(* ::Input:: *)
(*ESMFold["MTRSVSGNVWIIVGLAVWDVGGV"]*)


(* ::Input:: *)
(*ESMFold["MRSTNQLVSGNRHFIVTLLLBTLIPTTPIAKALRTDLTGTLRIVTKMFAATSTTTLPLTLPSSDQTDYQYAKADFLTDIDHMPFFMLSRTLDDFLLTDSSGRTITLALLTDLAD"]*)


(* ::Input:: *)
(*ESMFold["MRFRRRIFGWRWPLSIFDTHRPNANPQQLDTEFTMFRAFRSLRDTQLFDDVVGLGSDRVRGDAFQKAGLMIFSQTSDTDMTPLVQDEGIDTGTSLRV"]*)


(* ::Input:: *)
(*ESMFold["MRDLLQSKLTLIRQAKRDVTRTCRRDDQKTIADLRWFSFPTRMWWDPDQLDDGDDDEIDQGRSRDDDDDRRRDTLRDQLDTGDDHILIRSFGQSRTGFLSLTASGVRKGDDGSDLRDRDFVLGR"]*)


(* ::Input:: *)
(*ESMFold["MLWSDSTSAILTTRPLSDRWLRSIDSKBDPRDRTARRQISIFDGSSRLTIQLSLSTDGGIPQLRLRLMRSVASRGVLTDRDDHVFDSDITVFQRRARQARSSTTSIAFRRSGTIGRSRSD"]*)


(* ::Input:: *)
(*ESMFold["MGPLTLTTQLTLRDGDTSLDSDKTGAHDTTRSGRKLADFLAVRFDAKHLTGTPLLLLDVVVSDAIRATSPIRIVDLGTLTIIKLGRDLKWLTGSSEIFLDSSISLMLFLTRLFLS"]*)


(* ::Input:: *)
(*ESMFold["MTTSRQMQFVSFLFDHTFRNRTLEMRLFLLSRPSLSLSLLFRTGLFSRLRQQRRQIHDGGTDRLSVTDGDDLR"]*)


(* ::Input:: *)
(*ESMFold["MLWSDSTSAILTTRPLSDRWLRSIDSKBDPRDRTARRQISIFDGSSRLTIQLSLSTDGGIPQLRLRLMRSVASRGVLTDRDDHVFDSDITVFQRRARQARSSTTSIAFRRSGTIGRSRSD"]*)


(* ::Input:: *)
(*ESMFold["MQLLRSTVVATVIVDLKLLITDFSRRLDTRFDLKRRGLLQLLSTRRQPPHQRLKLIQLPSRQIDKSSVTLFISQISGTVGLDLQLDMISSKSSFDDVDLLFRSTSFRLLIQRPDSFGTKLSGD"]*)


(* ::Input:: *)
(*ESMFold["MGLGVFVLTTTPLLTTTFSTRLLAAGTTTTFTQLTRLTWFTTRTDTQEQRRDKGLTIKFSQTGDLRTTRRFQPRDKSFLLLLDQSSRRLWSSQRARTTTTMSRVKDTSQDLITSTGTTLSSD"]*)


(* ::Input:: *)
(*ESMFold["MRVRRGDDGGFDKLLLRGLLYVTPLARVDRPRLTDTKLKRDRTFTSSQRTRLTLPLDLRRRGDWQLRDRLARVAGRALSTIGQQQTFQIRLARRDAAAALLTQQDRLRGRSDRTTRRQVQLIPRL"]*)
